GET http://localhost:5000/api/users/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFjOTQwODQwZmM2OTdmNzhlYmJhZDQiLCJlbWFpbCI6Imx1aXMucHJpdGVAZ21haWwuY29tIiwiaWF0IjoxNzQ2ODcwOTY1LCJleHAiOjE3NDY4NzQ1NjV9.om3lVXebmchWbvcFywWLZWDhEwXQ7eUwBnqlLjyenaE HTTP/1.1
