POST http://localhost:5000/api/tasks/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFjOTM3YjYxODQwMzVlZmY0NTU0MWUiLCJlbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsImlhdCI6MTc0Njk1MzYzNywiZXhwIjoxNzQ2OTU3MjM3fQ.5mYLOStey4839TKMf_jEpSHF0Jq6BDYeTfVChxN0vsQ

{
    "body":"Продумать план отдыха на выходные",
    "createdAt":"2025-05-09",
    "deadline":"2025-05-09",
    "status":"DONE"
}